// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANoKy4Pa2f697l-UsD8RMxwAVDX-6XVI',
    appId: '1:916069274831:web:d8b9ab9e27f95d16e9d3ba',
    messagingSenderId: '916069274831',
    projectId: 'gigfind-25847',
    authDomain: 'gigfind-25847.firebaseapp.com',
    storageBucket: 'gigfind-25847.firebasestorage.app',
    measurementId: 'G-HH1TR1JYC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJ4jfmFLwA1b_ZJAjyzmXOXf67-0COxE',
    appId: '1:509620042580:android:ac6ecb7c834fbef102e6c1',
    messagingSenderId: '509620042580',
    projectId: 'gigs-c4fd5',
    storageBucket: 'gigs-c4fd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKFBkbN9tVZKso5I7uW18f3Mzb59kBtw',
    appId: '1:916069274831:ios:3418d0325ad7bf3ee9d3ba',
    messagingSenderId: '916069274831',
    projectId: 'gigfind-25847',
    storageBucket: 'gigfind-25847.firebasestorage.app',
    androidClientId: '916069274831-nq44uk03l9j2u9jheim1k1ha303egg38.apps.googleusercontent.com',
    iosClientId: '916069274831-fveruf7djvqpqcr4ve0v710fvk5pln1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigfind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKFBkbN9tVZKso5I7uW18f3Mzb59kBtw',
    appId: '1:916069274831:ios:3418d0325ad7bf3ee9d3ba',
    messagingSenderId: '916069274831',
    projectId: 'gigfind-25847',
    storageBucket: 'gigfind-25847.firebasestorage.app',
    iosBundleId: 'com.example.gigfind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBANoKy4Pa2f697l-UsD8RMxwAVDX-6XVI',
    appId: '1:916069274831:web:d162bd9409365585e9d3ba',
    messagingSenderId: '916069274831',
    projectId: 'gigfind-25847',
    authDomain: 'gigfind-25847.firebaseapp.com',
    storageBucket: 'gigfind-25847.firebasestorage.app',
    measurementId: 'G-CPRM98QLJJ',
  );
}